
####

GPU: [0,1]

VERBOSE: True

MODEL:
  SESSION: 'training_models'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1  #16 #8
  NUM_EPOCHS: 200
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256

  TRAIN_DIR_LABEL: ''        # path to training data'       # path to training data
  SAVE_DIR: './checkpoints'           # path to save models and images
  
